### PR TITLE
Add a $ sigil to built-in names

### PR DESCRIPTION
**Pull request by grncdr**
This makes it clearer for new-comers which things are provided by web-pockets and which aren't.

Since this could be considered ugly (and is definitely a breaking change) I'd like to hear opinions from known users.

/cc @madtrick @sdepold @ehd

### CODE REVIEW

**Comment by sdepold** [comment]
Hmm. Tricky. While it makes thinks clearer, it's also uglier. Did anyone complain about the current implementation?

**Comment by ehd** [comment]
Also not a big fan of the `$` prefix. Is there any other way to do visible namespacing?

**Comment by sdepold** [comment]
Instead of fixing the code we can probably just improve the documentation? :D

**Comment by ehd** [comment]
Thought that as well :D

**Comment by grncdr** [comment]
> Did anyone complain about the current implementation?

Not exactly, I asked someone for feedback after they had to work with an
existing app and they mentioned that figuring out which values were part of
the app or part of web-pockets was a stumbling block.

> Also not a big fan of the $ prefix. Is there any other way to do visible
namespacing?

Nothing I can think of except explicitly annotating functions or passing an
"injector" argument. In my opinion both of those are worse than prefixing
built-ins.

> Instead of fixing the code we can probably just improve the
documentation? :D

While the docs should _definitely_ be improved, that won't make the
web-pockets apps more comprehensible to the uninitiated.

However, I don't think this change will improve understanding enough to
offset the "ugliness cost" it imposes, so I will not merge this for now.

**Comment by grncdr** [comment]
Also on the subject of docs, some concrete suggestions would be most helpful. In particular, I find it difficult to come up with an overall structure that's comprehensible and inviting rather than just a wall of text. (Please open new issues with suggestions, or pull-requests if you're feeling especially enthusiastic ;))

**Comment by sdepold** [comment]
:D I might provide a PR at some point

**Comment by ehd** [comment]
@grncdr Sorry, I don't have any helpful suggestions right now. I didn't want to suggest the current docs are bad, just that if there's no list of built-ins linked from the TOC of the README that would be something to add. I enjoyed reading the docs so far!

**Comment by madtrick** [comment]
I was the one "complaining" about things being a bit obscure regarding parameters coming from the framework.

I know that prefixing those values with `$` is ugly but IMHO it provides a nice hint not only for newcomers but for all kinds of users. It's a simple but efficient way to "categorize" the parameters a handler takes.

**Comment by sdepold** [comment]
I see. Well. I wouldn't really mind the `$` too much /shrug

**Pull request closed without merging**
